name: Deploy to GitHub Pages

on:
  push:
    branches:
      - master

jobs:
  buildAndDeploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup Node.js
        uses: actions/setup-node@v3
      - name: Install Dependencies
        run: npm install
      - name: Build for Production
        run: npm run build
      - name: Deploy to GitHub Pages
        uses: actions/upload-pages-artifact@v1
        with:
          path: dist
